# Generated by Django 5.1.1 on 2024-09-18 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_of', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Porfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('site_url', models.URLField()),
                ('site_image', models.ImageField(upload_to='site_images/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('state_of', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.projectstate')),
                ('stacks', models.ManyToManyField(to='account.techstack')),
            ],
        ),
    ]
