# Generated by Django 5.1.1 on 2024-09-18 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_porfolio_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='porfolio',
            name='git_repo',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
