# Generated by Django 5.1.1 on 2024-09-21 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_state_of_porfolio_state_of_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porfolio',
            name='state_of_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.projectstate'),
        ),
    ]
